### ISSUE TITLE
RuntimeError: vgg

### ISSUE THREAD

**Issue by PaiDii** [IGLICT/StylizedNeRF#10]
Traceback (most recent call last):
  File "run_stylenerf.py", line 600, in <module>
    train(args=args)
  File "run_stylenerf.py", line 142, in train
    Prepare_Style_data(nerf_gen_data_path=nerf_gen_data_path)
  File "run_stylenerf.py", line 124, in Prepare_Style_data
    tmp_dataset = StyleRaySampler(data_path=args.datadir, style_path=args.styledir, factor=args.factor,
  File "/root/dataset.py", line 459, in __init__
    style_names, style_paths, style_images, style_features = style_data_prepare(style_path, images, size=512, chunk=8, sv_path=data_path + '/stylized_' + str(factor) + '/', decode_path='./pretrained/decoder.pth')
  File "/root/dataset.py", line 152, in style_data_prepare
    tmp_stylized_imgs, tmp_style_features = style_transfer(vgg=vgg, decoder=decoder, content=tmp_imgs, style=style[:tmp_imgs.shape[0]], alpha=1., return_feature=True)
  File "/root/dataset.py", line 65, in style_transfer
    content_f = vgg(content)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 23.26 GiB (GPU 0; 23.70 GiB total capacity; 2.21 GiB already allocated; 19.27 GiB free; 2.22 GiB reserved in total by PyTorch)

_**It still report this error when using larger GPU memory (80G), it will stack GPU memory, How can I solve it?**_

If you could provide some suggestions, I would greatly appreciate it!

**Comment by abhi-rf** [comment]
Hey @PaiDii How did you manage to solve this error? I tried almost every setting but this still prevails?
